# Generated by Django 4.2.7 on 2026-04-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='alerta',
            name='prioridad',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10),
        ),
        migrations.AddField(
            model_name='alerta',
            name='remitente',
            field=models.CharField(blank=True, default='Sistema', max_length=150),
        ),
        migrations.AddField(
            model_name='alerta',
            name='titulo',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='mensaje',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='tipo',
            field=models.CharField(choices=[('bajo_stock', 'Bajo Stock'), ('vencimiento', 'Vencimiento Próximo'), ('agotado', 'Agotado'), ('reactivo', 'Reactivo Crítico'), ('autorizacion', 'Autorización'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
    ]
