# Generated by Django 4.2.7 on 2026-04-22 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alerta',
            options={},
        ),
        migrations.AlterModelOptions(
            name='auditoria',
            options={},
        ),
        migrations.AlterModelOptions(
            name='historialcambio',
            options={},
        ),
        migrations.AlterModelOptions(
            name='movimiento',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={},
        ),
        migrations.RemoveField(
            model_name='historialcambio',
            name='objeto_id',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='evaluacion_seguridad',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_respuesta',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_solicitud',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='motivo_rechazo',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='prioridad',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='solicitante',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='alerta',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='mensaje',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='prioridad',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=20),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.producto'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='remitente',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='tipo',
            field=models.CharField(choices=[('bajo_stock', 'Bajo stock'), ('vencimiento', 'Por vencer'), ('otro', 'Otro')], default='otro', max_length=50),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='accion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='modulo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historialcambio',
            name='campo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='historialcambio',
            name='modelo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='historialcambio',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historialcambio',
            name='valor_anterior',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='historialcambio',
            name='valor_nuevo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='minimo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('reactivo', 'Reactivo'), ('insumo', 'Insumo'), ('equipo', 'Equipo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cargo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='institution',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
