# Generated by Django 4.2.7 on 2026-04-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_pedido_options_pedido_codigo_pedido_creado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='mensaje',
            field=models.TextField(blank=True, default=''),
        ),
    ]
