# Generated by Django 4.2.7 on 2026-04-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_make_alerta_mensaje_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='condicion_entrega',
            field=models.CharField(blank=True, choices=[('completa', 'Entrega completa — sin observaciones'), ('parcial', 'Entrega parcial — cantidad reducida'), ('observaciones', 'Con observaciones — requiere seguimiento'), ('urgente', 'Urgente — verificación necesaria')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='notas_entrega',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='responsable_entrega',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('entregado', 'Entregado')], default='pendiente', max_length=20),
        ),
    ]
